// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Hetic$Type } from "./Hetic";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Hetic"]: Hetic$Type;
    ["contracts/Hetic.sol:Hetic"]: Hetic$Type;
  }

  interface ContractTypesMap {
    ["Hetic"]: GetContractReturnType<Hetic$Type["abi"]>;
    ["contracts/Hetic.sol:Hetic"]: GetContractReturnType<Hetic$Type["abi"]>;
  }
}
