// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Bank$Type } from "./Bank";
import { IERC20$Type } from "./IERC20";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Bank"]: Bank$Type;
    ["IERC20"]: IERC20$Type;
    ["contracts/Bank.sol:Bank"]: Bank$Type;
    ["contracts/Bank.sol:IERC20"]: IERC20$Type;
  }

  interface ContractTypesMap {
    ["Bank"]: GetContractReturnType<Bank$Type["abi"]>;
    ["IERC20"]: GetContractReturnType<IERC20$Type["abi"]>;
    ["contracts/Bank.sol:Bank"]: GetContractReturnType<Bank$Type["abi"]>;
    ["contracts/Bank.sol:IERC20"]: GetContractReturnType<IERC20$Type["abi"]>;
  }
}
